FROM python:3.10-slim

WORKDIR /app

COPY scripts/documentai_token_extraction.py scripts/
COPY docker/requirements/requirements_docai.txt .
RUN pip install --no-cache-dir -r requirements_docai.txt

COPY config/ /app/config/

ENTRYPOINT ["/app/entrypoint.sh"]
CMD ["documentai_token_extraction"]